spring:
# Configurações do banco de dados
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

    jpa:
      hibernate:
        ddl-auto: create-drop
        show-sql: true
      properties:
        hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  application:
    name: api-rest-terra-tech

#level de log
logging:
  level:
    root: INFO
    org:
      springframework:
        web: DEBUG