openapi: "3.0.1"
info:
  title: "Terratech API"
  version: "v0"
  description: "api do projeto terra tech"

servers:
  - url: "http://localhost:8080"
    description: "Local server"

paths:
  /v1/users:
    post:
      tags:
        - user-controller
      operationId: post
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserRequest"
        required: true
      responses:
        200:
          description: OK
          content:
            '*/*':
              schema:
                type: string

        409:
          description: Conflict
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResponse"

        500:
          description: Internal Server Error
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /v1/users/{id}:
    get:
      tags:
        - user-controller
      operationId: getOne
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: OK
          content:
            '*/*':
              schema:
                type: string
        500:
          description: Internal Server Error
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorResponse"

components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
        status:
          type: integer
          format: int32
        timestamp:
          type: string
    UserRequest:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
        dateOfBirth:
          type: string
          format: date
        cep:
          type: string
        number:
          type: string
